import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoMigration1768297408965 implements MigrationInterface {
    name = 'AutoMigration1768297408965'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "fk_assets_category"`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" DROP CONSTRAINT "asset_assignments_asset_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" DROP CONSTRAINT "asset_assignments_employee_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assets_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."uq_one_active_assignment_per_asset"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assignments_asset_assigned_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_assignments_employee_assigned_at"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "employees_employee_no_key"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "employee_no"`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "employee_no" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "UQ_d9efe9b7b295017edab1ef9d7b6" UNIQUE ("employee_no")`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "full_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "employees_email_key"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "UQ_765bc1ac8967533a04c74a9f6af" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TYPE "public"."employee_status" RENAME TO "employee_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."employees_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" TYPE "public"."employees_status_enum" USING "status"::"text"::"public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employee_status_old"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP CONSTRAINT "asset_categories_name_key"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD CONSTRAINT "UQ_72175ada98a0852411360e3a48d" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "assets_asset_tag_key"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "asset_tag"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "asset_tag" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "UQ_490daec7711d8e8bedd6a5a7caa" UNIQUE ("asset_tag")`);
        await queryRunner.query(`ALTER TYPE "public"."asset_status" RENAME TO "asset_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."assets_status_enum" AS ENUM('NEW', 'USED', 'DAMAGED', 'MISSING')`);
        await queryRunner.query(`ALTER TABLE "assets" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "assets" ALTER COLUMN "status" TYPE "public"."assets_status_enum" USING "status"::"text"::"public"."assets_status_enum"`);
        await queryRunner.query(`ALTER TABLE "assets" ALTER COLUMN "status" SET DEFAULT 'USED'`);
        await queryRunner.query(`DROP TYPE "public"."asset_status_old"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "brand"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "brand" character varying`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "model"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "model" character varying`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "assets_serial_no_key"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "serial_no"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "serial_no" character varying`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "UQ_af611c8cdf82233955861757e1e" UNIQUE ("serial_no")`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" DROP COLUMN "assigned_by"`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" ADD "assigned_by" character varying`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "FK_bfdc3fe63eb7269f4a286252641" FOREIGN KEY ("category_id") REFERENCES "asset_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" ADD CONSTRAINT "FK_3b81c0dcc6a4264cbd0b548fa7b" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" ADD CONSTRAINT "FK_89adfcc609a9ae60380cba94cad" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "asset_assignments" DROP CONSTRAINT "FK_89adfcc609a9ae60380cba94cad"`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" DROP CONSTRAINT "FK_3b81c0dcc6a4264cbd0b548fa7b"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "FK_bfdc3fe63eb7269f4a286252641"`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" DROP COLUMN "assigned_by"`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" ADD "assigned_by" text`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "UQ_af611c8cdf82233955861757e1e"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "serial_no"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "serial_no" text`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "assets_serial_no_key" UNIQUE ("serial_no")`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "model"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "model" text`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "brand"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "brand" text`);
        await queryRunner.query(`CREATE TYPE "public"."asset_status_old" AS ENUM('NEW', 'USED', 'DAMAGED', 'MISSING')`);
        await queryRunner.query(`ALTER TABLE "assets" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "assets" ALTER COLUMN "status" TYPE "public"."asset_status_old" USING "status"::"text"::"public"."asset_status_old"`);
        await queryRunner.query(`ALTER TABLE "assets" ALTER COLUMN "status" SET DEFAULT 'USED'`);
        await queryRunner.query(`DROP TYPE "public"."assets_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."asset_status_old" RENAME TO "asset_status"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP CONSTRAINT "UQ_490daec7711d8e8bedd6a5a7caa"`);
        await queryRunner.query(`ALTER TABLE "assets" DROP COLUMN "asset_tag"`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "asset_tag" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "assets_asset_tag_key" UNIQUE ("asset_tag")`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP CONSTRAINT "UQ_72175ada98a0852411360e3a48d"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD CONSTRAINT "asset_categories_name_key" UNIQUE ("name")`);
        await queryRunner.query(`CREATE TYPE "public"."employee_status_old" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" TYPE "public"."employee_status_old" USING "status"::"text"::"public"."employee_status_old"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."employees_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."employee_status_old" RENAME TO "employee_status"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "UQ_765bc1ac8967533a04c74a9f6af"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "employees_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "full_name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "UQ_d9efe9b7b295017edab1ef9d7b6"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "employee_no"`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "employee_no" text`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "employees_employee_no_key" UNIQUE ("employee_no")`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "assets" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "asset_categories" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_assignments_employee_assigned_at" ON "asset_assignments" ("assigned_at", "employee_id") `);
        await queryRunner.query(`CREATE INDEX "idx_assignments_asset_assigned_at" ON "asset_assignments" ("asset_id", "assigned_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_one_active_assignment_per_asset" ON "asset_assignments" ("asset_id") WHERE (unassigned_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_assets_category_id" ON "assets" ("category_id") `);
        await queryRunner.query(`ALTER TABLE "asset_assignments" ADD CONSTRAINT "asset_assignments_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "asset_assignments" ADD CONSTRAINT "asset_assignments_asset_id_fkey" FOREIGN KEY ("asset_id") REFERENCES "assets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assets" ADD CONSTRAINT "fk_assets_category" FOREIGN KEY ("category_id") REFERENCES "asset_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
